todo:
    path: .issues
    default_status: draft
    default_type: task
    sync:
        github:
            repo: toba/musup
changelog: weekly
packages: [brew, scoop]
citations:
    - repo: dhowden/tag
      branch: master
      notes: ID3, MP4 and OGG/FLAC metadata parsing in Go
      last_checked_sha: 3d75831295e8a3dfbf59ed763169b22da6451186
      last_checked_date: "2026-04-21T21:53:59Z"
      paths:
        high: ['**/*.go']
        medium: [go.mod, go.sum]
        low: [.github/**, README.md, LICENSE]
    - repo: michiwend/gomusicbrainz
      branch: master
      notes: a Go (Golang) MusicBrainz WS2 client library - work in progress
      last_checked_sha: 6c07e13dd396ba10bd9f8904be5018df94472839
      last_checked_date: "2026-04-21T21:53:59Z"
      paths:
        high: ['**/*.go']
        low: [.github/**, README.md, LICENSE]
    - repo: charmbracelet/lipgloss
      branch: main
      notes: Style definitions for nice terminal layouts
      last_checked_sha: 9cbfe8b6a61bf48d35db4499853681fdbaaea31a
      last_checked_date: "2026-04-21T21:53:59Z"
      paths:
        high: ['**/*.go']
        medium: [go.mod, go.sum]
        low: [.github/**, README.md, LICENSE]
    - repo: charmbracelet/bubbletea
      branch: main
      notes: A powerful little TUI framework
      last_checked_sha: 074596e14e2f5ca5e3986ee72e7c08f1569c4178
      last_checked_date: "2026-04-21T21:53:59Z"
      paths:
        high: ['**/*.go']
        medium: [go.mod, go.sum]
        low: [.github/**, README.md, LICENSE]
    - repo: charmbracelet/bubbles
      branch: main
      notes: TUI components for Bubble Tea
      last_checked_sha: 6feda242335b791e5b81cc05166236eb753be865
      last_checked_date: "2026-04-21T21:53:59Z"
      paths:
        high: ['**/*.go']
        medium: [go.mod, go.sum]
        low: [.github/**, README.md, LICENSE]
