// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file.sql

package model

import (
	"context"
)

const allFileMeta = `-- name: AllFileMeta :many
SELECT path, size, mod_time, title FROM files
`

type AllFileMetaRow struct {
	Path    string
	Size    int64
	ModTime string
	Title   string
}

func (q *Queries) AllFileMeta(ctx context.Context) ([]AllFileMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, allFileMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllFileMetaRow
	for rows.Next() {
		var i AllFileMetaRow
		if err := rows.Scan(
			&i.Path,
			&i.Size,
			&i.ModTime,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allFilePaths = `-- name: AllFilePaths :many
SELECT path FROM files
`

func (q *Queries) AllFilePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, allFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFileByPath = `-- name: DeleteFileByPath :exec
DELETE FROM files WHERE path = ?
`

func (q *Queries) DeleteFileByPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteFileByPath, path)
	return err
}

const localAlbums = `-- name: LocalAlbums :many
SELECT DISTINCT album FROM files WHERE artist_norm = ? AND album != '' ORDER BY album
`

func (q *Queries) LocalAlbums(ctx context.Context, artistNorm string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, localAlbums, artistNorm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var album string
		if err := rows.Scan(&album); err != nil {
			return nil, err
		}
		items = append(items, album)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uniqueArtists = `-- name: UniqueArtists :many
SELECT DISTINCT artist FROM files WHERE artist != '' ORDER BY artist
`

func (q *Queries) UniqueArtists(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, uniqueArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var artist string
		if err := rows.Scan(&artist); err != nil {
			return nil, err
		}
		items = append(items, artist)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFile = `-- name: UpsertFile :exec
INSERT INTO files (path, size, mod_time, artist, album, title, track_number, is_album_artist, scanned_at, title_norm, album_norm, artist_norm)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    size            = excluded.size,
    mod_time        = excluded.mod_time,
    artist          = excluded.artist,
    album           = excluded.album,
    title           = excluded.title,
    track_number    = excluded.track_number,
    is_album_artist = excluded.is_album_artist,
    scanned_at      = excluded.scanned_at,
    title_norm      = excluded.title_norm,
    album_norm      = excluded.album_norm,
    artist_norm     = excluded.artist_norm
`

type UpsertFileParams struct {
	Path          string
	Size          int64
	ModTime       string
	Artist        string
	Album         string
	Title         string
	TrackNumber   int64
	IsAlbumArtist int64
	ScannedAt     string
	TitleNorm     string
	AlbumNorm     string
	ArtistNorm    string
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertFile,
		arg.Path,
		arg.Size,
		arg.ModTime,
		arg.Artist,
		arg.Album,
		arg.Title,
		arg.TrackNumber,
		arg.IsAlbumArtist,
		arg.ScannedAt,
		arg.TitleNorm,
		arg.AlbumNorm,
		arg.ArtistNorm,
	)
	return err
}
