// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album.sql

package db

import (
	"context"
)

const getAlbumID = `-- name: GetAlbumID :one
SELECT id FROM albums WHERE artist_id = ? AND title = ?
`

func (q *Queries) GetAlbumID(ctx context.Context, artistID int64, title string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAlbumID, artistID, title)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAlbumsByArtist = `-- name: ListAlbumsByArtist :many
SELECT ar.name, al.title, al.mbid, al.release_date, al.primary_type,
       al.secondary_types, CAST(COALESCE(t.total, 0) AS INTEGER) AS total_tracks, CAST(COALESCE(t.local, 0) AS INTEGER) AS local_tracks
FROM albums al
JOIN artists ar ON ar.id = al.artist_id
LEFT JOIN (
    SELECT album_id,
           COUNT(*) AS total,
           SUM(local) AS local
    FROM tracks
    GROUP BY album_id
) t ON t.album_id = al.id
WHERE ar.name_norm = ?
ORDER BY al.release_date ASC, al.title ASC
`

type ListAlbumsByArtistRow struct {
	Name           string
	Title          string
	Mbid           string
	ReleaseDate    string
	PrimaryType    string
	SecondaryTypes string
	TotalTracks    int64
	LocalTracks    int64
}

func (q *Queries) ListAlbumsByArtist(ctx context.Context, nameNorm string) ([]ListAlbumsByArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByArtist, nameNorm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByArtistRow
	for rows.Next() {
		var i ListAlbumsByArtistRow
		if err := rows.Scan(
			&i.Name,
			&i.Title,
			&i.Mbid,
			&i.ReleaseDate,
			&i.PrimaryType,
			&i.SecondaryTypes,
			&i.TotalTracks,
			&i.LocalTracks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnownAlbumMBIDs = `-- name: ListKnownAlbumMBIDs :many
SELECT DISTINCT al.mbid
FROM albums al
JOIN artists ar ON ar.id = al.artist_id
JOIN tracks t ON t.album_id = al.id
WHERE ar.name_norm = ? AND al.mbid != ''
`

func (q *Queries) ListKnownAlbumMBIDs(ctx context.Context, nameNorm string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listKnownAlbumMBIDs, nameNorm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var mbid string
		if err := rows.Scan(&mbid); err != nil {
			return nil, err
		}
		items = append(items, mbid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlbum = `-- name: UpsertAlbum :execlastid
INSERT INTO albums (artist_id, title, title_norm, mbid, release_date, primary_type, secondary_types)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(artist_id, title) DO UPDATE SET
    title_norm      = excluded.title_norm,
    mbid            = excluded.mbid,
    release_date    = excluded.release_date,
    primary_type    = excluded.primary_type,
    secondary_types = excluded.secondary_types
`

type UpsertAlbumParams struct {
	ArtistID       int64
	Title          string
	TitleNorm      string
	Mbid           string
	ReleaseDate    string
	PrimaryType    string
	SecondaryTypes string
}

func (q *Queries) UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertAlbum,
		arg.ArtistID,
		arg.Title,
		arg.TitleNorm,
		arg.Mbid,
		arg.ReleaseDate,
		arg.PrimaryType,
		arg.SecondaryTypes,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
