// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artist.sql

package db

import (
	"context"
)

const albumArtists = `-- name: AlbumArtists :many
SELECT ar.id, ar.name, ar.followed, ar.inactive, ar.reviewed_at,
       CAST(COALESCE((SELECT MAX(al.release_date) FROM albums al WHERE al.artist_id = ar.id), '') AS TEXT) AS latest_release
FROM artists ar
WHERE ar.id IN (
    SELECT artist_id FROM files
    WHERE artist != '' AND album != '' AND artist_id != 0
    GROUP BY artist_id
    HAVING MAX(is_album_artist) = 1
)
ORDER BY
  CASE
    WHEN ar.name LIKE 'The %' THEN SUBSTR(ar.name, 5)
    WHEN ar.name LIKE 'A %'   THEN SUBSTR(ar.name, 3)
    ELSE ar.name
  END COLLATE NOCASE
`

type AlbumArtistsRow struct {
	ID            int64
	Name          string
	Followed      int64
	Inactive      int64
	ReviewedAt    string
	LatestRelease string
}

// All album artists with their followed status, for the TUI.
func (q *Queries) AlbumArtists(ctx context.Context) ([]AlbumArtistsRow, error) {
	rows, err := q.db.QueryContext(ctx, albumArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumArtistsRow
	for rows.Next() {
		var i AlbumArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Followed,
			&i.Inactive,
			&i.ReviewedAt,
			&i.LatestRelease,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, name_norm, mbid, last_checked_at, not_found
FROM artists WHERE id = ?
`

type GetArtistByIDRow struct {
	ID            int64
	Name          string
	NameNorm      string
	Mbid          string
	LastCheckedAt string
	NotFound      int64
}

func (q *Queries) GetArtistByID(ctx context.Context, id int64) (GetArtistByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getArtistByID, id)
	var i GetArtistByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNorm,
		&i.Mbid,
		&i.LastCheckedAt,
		&i.NotFound,
	)
	return i, err
}

const getArtistByNameNorm = `-- name: GetArtistByNameNorm :one
SELECT id, name, mbid, last_checked_at, not_found
FROM artists WHERE name_norm = ?
`

type GetArtistByNameNormRow struct {
	ID            int64
	Name          string
	Mbid          string
	LastCheckedAt string
	NotFound      int64
}

func (q *Queries) GetArtistByNameNorm(ctx context.Context, nameNorm string) (GetArtistByNameNormRow, error) {
	row := q.db.QueryRowContext(ctx, getArtistByNameNorm, nameNorm)
	var i GetArtistByNameNormRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mbid,
		&i.LastCheckedAt,
		&i.NotFound,
	)
	return i, err
}

const insertArtist = `-- name: InsertArtist :execlastid
INSERT INTO artists (name, name_norm) VALUES (?, ?)
`

func (q *Queries) InsertArtist(ctx context.Context, name string, nameNorm string) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertArtist, name, nameNorm)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const markArtistNotFound = `-- name: MarkArtistNotFound :exec
UPDATE artists SET not_found = 1 WHERE id = ?
`

func (q *Queries) MarkArtistNotFound(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markArtistNotFound, id)
	return err
}

const setFollowed = `-- name: SetFollowed :exec
UPDATE artists SET followed = ? WHERE id = ?
`

func (q *Queries) SetFollowed(ctx context.Context, followed int64, iD int64) error {
	_, err := q.db.ExecContext(ctx, setFollowed, followed, iD)
	return err
}

const setInactive = `-- name: SetInactive :exec
UPDATE artists SET inactive = ? WHERE id = ?
`

func (q *Queries) SetInactive(ctx context.Context, inactive int64, iD int64) error {
	_, err := q.db.ExecContext(ctx, setInactive, inactive, iD)
	return err
}

const setReviewedAt = `-- name: SetReviewedAt :exec
UPDATE artists SET reviewed_at = ? WHERE id = ?
`

func (q *Queries) SetReviewedAt(ctx context.Context, reviewedAt string, iD int64) error {
	_, err := q.db.ExecContext(ctx, setReviewedAt, reviewedAt, iD)
	return err
}

const updateArtistFull = `-- name: UpdateArtistFull :exec
UPDATE artists SET
    mbid = ?, last_checked_at = ?, not_found = ?
WHERE id = ?
`

func (q *Queries) UpdateArtistFull(ctx context.Context, mbid string, lastCheckedAt string, notFound int64, iD int64) error {
	_, err := q.db.ExecContext(ctx, updateArtistFull,
		mbid,
		lastCheckedAt,
		notFound,
		iD,
	)
	return err
}

const updateArtistMeta = `-- name: UpdateArtistMeta :exec
UPDATE artists SET mbid = ?, last_checked_at = ? WHERE id = ?
`

func (q *Queries) UpdateArtistMeta(ctx context.Context, mbid string, lastCheckedAt string, iD int64) error {
	_, err := q.db.ExecContext(ctx, updateArtistMeta, mbid, lastCheckedAt, iD)
	return err
}
