// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artist.sql

package db

import (
	"context"
)

const getArtistByNameNorm = `-- name: GetArtistByNameNorm :one
SELECT id, name, mbid, last_checked_at, not_found
FROM artists WHERE name_norm = ?
`

type GetArtistByNameNormRow struct {
	ID            int64
	Name          string
	Mbid          string
	LastCheckedAt string
	NotFound      int64
}

func (q *Queries) GetArtistByNameNorm(ctx context.Context, nameNorm string) (GetArtistByNameNormRow, error) {
	row := q.db.QueryRowContext(ctx, getArtistByNameNorm, nameNorm)
	var i GetArtistByNameNormRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mbid,
		&i.LastCheckedAt,
		&i.NotFound,
	)
	return i, err
}

const insertArtist = `-- name: InsertArtist :execlastid
INSERT INTO artists (name, name_norm) VALUES (?, ?)
`

func (q *Queries) InsertArtist(ctx context.Context, name string, nameNorm string) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertArtist, name, nameNorm)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const markArtistNotFound = `-- name: MarkArtistNotFound :exec
UPDATE artists SET not_found = 1 WHERE id = ?
`

func (q *Queries) MarkArtistNotFound(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markArtistNotFound, id)
	return err
}

const updateArtistFull = `-- name: UpdateArtistFull :exec
UPDATE artists SET
    mbid = ?, last_checked_at = ?, not_found = ?
WHERE id = ?
`

func (q *Queries) UpdateArtistFull(ctx context.Context, mbid string, lastCheckedAt string, notFound int64, iD int64) error {
	_, err := q.db.ExecContext(ctx, updateArtistFull,
		mbid,
		lastCheckedAt,
		notFound,
		iD,
	)
	return err
}

const updateArtistMeta = `-- name: UpdateArtistMeta :exec
UPDATE artists SET mbid = ?, last_checked_at = ? WHERE id = ?
`

func (q *Queries) UpdateArtistMeta(ctx context.Context, mbid string, lastCheckedAt string, iD int64) error {
	_, err := q.db.ExecContext(ctx, updateArtistMeta, mbid, lastCheckedAt, iD)
	return err
}
