// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artist.sql

package db

import (
	"context"
)

const artistSummaries = `-- name: ArtistSummaries :many
WITH
  file_stats AS (
    SELECT artist_norm,
           COUNT(DISTINCT album) AS album_cnt,
           COALESCE(MAX(CASE WHEN album != '' THEN album END), '') AS newest,
           COUNT(*) AS track_cnt
    FROM files
    WHERE artist != ''
    GROUP BY artist_norm
    HAVING MAX(is_album_artist) = 1
  ),
  display_names AS (
    SELECT artist_norm, artist AS name
    FROM (
      SELECT artist_norm, artist,
             ROW_NUMBER() OVER (PARTITION BY artist_norm ORDER BY COUNT(*) DESC) AS rn
      FROM files
      WHERE artist != ''
      GROUP BY artist_norm, artist
    )
    WHERE rn = 1
  ),
  album_counts AS (
    SELECT ar.name_norm, COUNT(*) AS total_albums
    FROM albums al JOIN artists ar ON ar.id = al.artist_id
    GROUP BY ar.name_norm
  ),
  track_counts AS (
    SELECT ar.name_norm,
           COUNT(*) AS total_tracks,
           SUM(t.local) AS local_tracks,
           COUNT(DISTINCT CASE WHEN t.local = 1 THEN al.id END) AS local_albums
    FROM tracks t
    JOIN albums al ON al.id = t.album_id
    JOIN artists ar ON ar.id = al.artist_id
    GROUP BY ar.name_norm
  ),
  max_local_date AS (
    SELECT ar.name_norm, MAX(al.release_date) AS max_date
    FROM albums al
    JOIN artists ar ON ar.id = al.artist_id
    JOIN tracks t ON t.album_id = al.id
    WHERE t.local = 1
    GROUP BY ar.name_norm
  ),
  latest_release_date AS (
    SELECT ar.name_norm, MAX(al.release_date) AS max_date
    FROM albums al
    JOIN artists ar ON ar.id = al.artist_id
    GROUP BY ar.name_norm
  ),
  has_new AS (
    SELECT ar.name_norm
    FROM albums al
    JOIN artists ar ON ar.id = al.artist_id
    LEFT JOIN max_local_date mld ON mld.name_norm = ar.name_norm
    WHERE al.release_date > MAX(COALESCE(mld.max_date, ''), COALESCE(ar.reviewed_at, ''))
    GROUP BY ar.name_norm
  )
SELECT dn.name,
       CAST(fs.album_cnt AS INTEGER) AS album_cnt,
       CAST(fs.newest AS TEXT) AS newest,
       CAST(fs.track_cnt AS INTEGER) AS track_cnt,
       CAST(COALESCE(a.mbid, '') AS TEXT) AS mbid,
       CAST(COALESCE(ac.total_albums, 0) AS INTEGER) AS total_albums,
       CAST(COALESCE(tc.total_tracks, 0) AS INTEGER) AS total_tracks,
       CAST(COALESCE(a.followed, 1) AS INTEGER) AS followed,
       CAST(CASE WHEN hn.name_norm IS NOT NULL THEN 1 ELSE 0 END AS INTEGER) AS has_new,
       CAST(COALESCE(tc.local_tracks, 0) AS INTEGER) AS local_tracks,
       CAST(COALESCE(tc.local_albums, 0) AS INTEGER) AS local_albums,
       CAST(COALESCE(lrd.max_date, '') AS TEXT) AS latest_date
FROM file_stats fs
JOIN display_names dn ON dn.artist_norm = fs.artist_norm
LEFT JOIN artists a ON a.name_norm = fs.artist_norm
LEFT JOIN album_counts ac ON ac.name_norm = fs.artist_norm
LEFT JOIN track_counts tc ON tc.name_norm = fs.artist_norm
LEFT JOIN has_new hn ON hn.name_norm = fs.artist_norm
LEFT JOIN latest_release_date lrd ON lrd.name_norm = fs.artist_norm
ORDER BY fs.artist_norm
`

type ArtistSummariesRow struct {
	Name        string
	AlbumCnt    int64
	Newest      string
	TrackCnt    int64
	Mbid        string
	TotalAlbums int64
	TotalTracks int64
	Followed    int64
	HasNew      int64
	LocalTracks int64
	LocalAlbums int64
	LatestDate  string
}

func (q *Queries) ArtistSummaries(ctx context.Context) ([]ArtistSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, artistSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistSummariesRow
	for rows.Next() {
		var i ArtistSummariesRow
		if err := rows.Scan(
			&i.Name,
			&i.AlbumCnt,
			&i.Newest,
			&i.TrackCnt,
			&i.Mbid,
			&i.TotalAlbums,
			&i.TotalTracks,
			&i.Followed,
			&i.HasNew,
			&i.LocalTracks,
			&i.LocalAlbums,
			&i.LatestDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistByNameNorm = `-- name: GetArtistByNameNorm :one
SELECT id, name, mbid, last_checked_at, not_found
FROM artists WHERE name_norm = ?
`

type GetArtistByNameNormRow struct {
	ID            int64
	Name          string
	Mbid          string
	LastCheckedAt string
	NotFound      int64
}

func (q *Queries) GetArtistByNameNorm(ctx context.Context, nameNorm string) (GetArtistByNameNormRow, error) {
	row := q.db.QueryRowContext(ctx, getArtistByNameNorm, nameNorm)
	var i GetArtistByNameNormRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mbid,
		&i.LastCheckedAt,
		&i.NotFound,
	)
	return i, err
}

const getFollowed = `-- name: GetFollowed :one
SELECT followed FROM artists WHERE name_norm = ?
`

func (q *Queries) GetFollowed(ctx context.Context, nameNorm string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFollowed, nameNorm)
	var followed int64
	err := row.Scan(&followed)
	return followed, err
}

const insertArtist = `-- name: InsertArtist :execlastid
INSERT INTO artists (name, name_norm) VALUES (?, ?)
`

func (q *Queries) InsertArtist(ctx context.Context, name string, nameNorm string) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertArtist, name, nameNorm)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listUnfollowedArtistNames = `-- name: ListUnfollowedArtistNames :many
SELECT name FROM artists WHERE followed = 0
`

func (q *Queries) ListUnfollowedArtistNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnfollowedArtistNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArtistNotFound = `-- name: MarkArtistNotFound :exec
UPDATE artists SET not_found = 1 WHERE id = ?
`

func (q *Queries) MarkArtistNotFound(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markArtistNotFound, id)
	return err
}

const markReviewed = `-- name: MarkReviewed :exec
UPDATE artists SET reviewed_at = COALESCE(
    (SELECT MAX(al.release_date) FROM albums al WHERE al.artist_id = ?1),
    ''
) WHERE artists.id = ?1
`

func (q *Queries) MarkReviewed(ctx context.Context, artistID int64) error {
	_, err := q.db.ExecContext(ctx, markReviewed, artistID)
	return err
}

const setFollowed = `-- name: SetFollowed :exec
UPDATE artists SET followed = ? WHERE id = ?
`

func (q *Queries) SetFollowed(ctx context.Context, followed int64, iD int64) error {
	_, err := q.db.ExecContext(ctx, setFollowed, followed, iD)
	return err
}

const updateArtistFull = `-- name: UpdateArtistFull :exec
UPDATE artists SET
    mbid = ?, last_checked_at = ?, not_found = ?
WHERE id = ?
`

func (q *Queries) UpdateArtistFull(ctx context.Context, mbid string, lastCheckedAt string, notFound int64, iD int64) error {
	_, err := q.db.ExecContext(ctx, updateArtistFull,
		mbid,
		lastCheckedAt,
		notFound,
		iD,
	)
	return err
}

const updateArtistMeta = `-- name: UpdateArtistMeta :exec
UPDATE artists SET mbid = ?, last_checked_at = ? WHERE id = ?
`

func (q *Queries) UpdateArtistMeta(ctx context.Context, mbid string, lastCheckedAt string, iD int64) error {
	_, err := q.db.ExecContext(ctx, updateArtistMeta, mbid, lastCheckedAt, iD)
	return err
}
