// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file.sql

package db

import (
	"context"
)

const allFileMeta = `-- name: AllFileMeta :many
SELECT path, size, mod_time, title FROM files
`

type AllFileMetaRow struct {
	Path    string
	Size    int64
	ModTime string
	Title   string
}

func (q *Queries) AllFileMeta(ctx context.Context) ([]AllFileMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, allFileMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllFileMetaRow
	for rows.Next() {
		var i AllFileMetaRow
		if err := rows.Scan(
			&i.Path,
			&i.Size,
			&i.ModTime,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allFilePaths = `-- name: AllFilePaths :many
SELECT path FROM files
`

func (q *Queries) AllFilePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, allFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const artistLocalTracks = `-- name: ArtistLocalTracks :many
SELECT f.path, f.album, f.track_number, f.title,
       CAST(COALESCE(al.release_date, '') AS TEXT) AS release_date
FROM files f
LEFT JOIN albums al ON al.artist_id = f.artist_id AND al.title_norm = f.album_norm
WHERE f.artist_id = ? AND f.album != ''
ORDER BY f.album COLLATE NOCASE, f.track_number, f.title COLLATE NOCASE
`

type ArtistLocalTracksRow struct {
	Path        string
	Album       string
	TrackNumber int64
	Title       string
	ReleaseDate string
}

func (q *Queries) ArtistLocalTracks(ctx context.Context, artistID int64) ([]ArtistLocalTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, artistLocalTracks, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtistLocalTracksRow
	for rows.Next() {
		var i ArtistLocalTracksRow
		if err := rows.Scan(
			&i.Path,
			&i.Album,
			&i.TrackNumber,
			&i.Title,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFileByPath = `-- name: DeleteFileByPath :exec
DELETE FROM files WHERE path = ?
`

func (q *Queries) DeleteFileByPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteFileByPath, path)
	return err
}

const distinctArtistIDs = `-- name: DistinctArtistIDs :many
SELECT DISTINCT f.artist_id FROM files f
JOIN artists a ON a.id = f.artist_id
WHERE f.artist != '' AND f.is_album_artist = 1 AND f.artist_id != 0
  AND a.followed = 1
`

func (q *Queries) DistinctArtistIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, distinctArtistIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var artist_id int64
		if err := rows.Scan(&artist_id); err != nil {
			return nil, err
		}
		items = append(items, artist_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFile = `-- name: UpsertFile :exec
INSERT INTO files (path, size, mod_time, artist, album, title, track_number, is_album_artist, scanned_at, title_norm, album_norm, artist_norm, artist_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    size            = excluded.size,
    mod_time        = excluded.mod_time,
    artist          = excluded.artist,
    album           = excluded.album,
    title           = excluded.title,
    track_number    = excluded.track_number,
    is_album_artist = excluded.is_album_artist,
    scanned_at      = excluded.scanned_at,
    title_norm      = excluded.title_norm,
    album_norm      = excluded.album_norm,
    artist_norm     = excluded.artist_norm,
    artist_id       = excluded.artist_id
`

type UpsertFileParams struct {
	Path          string
	Size          int64
	ModTime       string
	Artist        string
	Album         string
	Title         string
	TrackNumber   int64
	IsAlbumArtist int64
	ScannedAt     string
	TitleNorm     string
	AlbumNorm     string
	ArtistNorm    string
	ArtistID      int64
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertFile,
		arg.Path,
		arg.Size,
		arg.ModTime,
		arg.Artist,
		arg.Album,
		arg.Title,
		arg.TrackNumber,
		arg.IsAlbumArtist,
		arg.ScannedAt,
		arg.TitleNorm,
		arg.AlbumNorm,
		arg.ArtistNorm,
		arg.ArtistID,
	)
	return err
}
