// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Album struct {
	ID             int64
	ArtistID       int64
	Title          string
	TitleNorm      string
	Mbid           string
	ReleaseDate    string
	PrimaryType    string
	SecondaryTypes string
}

type Artist struct {
	ID            int64
	Name          string
	NameNorm      string
	Mbid          string
	LastCheckedAt string
	NotFound      int64
	Followed      int64
	ReviewedAt    string
}

type File struct {
	Path          string
	Size          int64
	ModTime       string
	Artist        string
	ArtistNorm    string
	Album         string
	AlbumNorm     string
	Title         string
	TitleNorm     string
	TrackNumber   int64
	IsAlbumArtist int64
	ScannedAt     string
}

type Track struct {
	ID        int64
	AlbumID   int64
	Title     string
	TitleNorm string
	Position  int64
	Mbid      string
	LengthMs  int64
	Local     int64
}
