// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prune.sql

package db

import (
	"context"
)

const deleteUnfollowedAlbums = `-- name: DeleteUnfollowedAlbums :execrows
DELETE FROM albums WHERE artist_id IN (
    SELECT id FROM artists WHERE followed = 0
)
`

func (q *Queries) DeleteUnfollowedAlbums(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnfollowedAlbums)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnfollowedArtists = `-- name: DeleteUnfollowedArtists :execrows
DELETE FROM artists WHERE followed = 0
`

func (q *Queries) DeleteUnfollowedArtists(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnfollowedArtists)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnfollowedTracks = `-- name: DeleteUnfollowedTracks :execrows
DELETE FROM tracks WHERE album_id IN (
    SELECT al.id FROM albums al
    JOIN artists ar ON ar.id = al.artist_id
    WHERE ar.followed = 0
)
`

func (q *Queries) DeleteUnfollowedTracks(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnfollowedTracks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
