// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AllFileMeta(ctx context.Context) ([]AllFileMetaRow, error)
	AllFilePaths(ctx context.Context) ([]string, error)
	DeleteFileByPath(ctx context.Context, path string) error
	DistinctArtistNorms(ctx context.Context) ([]string, error)
	GetArtistByNameNorm(ctx context.Context, nameNorm string) (GetArtistByNameNormRow, error)
	InsertArtist(ctx context.Context, name string, nameNorm string) (int64, error)
	MarkArtistNotFound(ctx context.Context, id int64) error
	// Artists with MB albums released since cutoff that aren't in local files.
	NewerReleases(ctx context.Context, releaseDate string) ([]NewerReleasesRow, error)
	UpdateArtistFull(ctx context.Context, mbid string, lastCheckedAt string, notFound int64, iD int64) error
	UpdateArtistMeta(ctx context.Context, mbid string, lastCheckedAt string, iD int64) error
	UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) error
	UpsertFile(ctx context.Context, arg UpsertFileParams) error
}

var _ Querier = (*Queries)(nil)
