// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track.sql

package db

import (
	"context"
)

const listTracksByAlbum = `-- name: ListTracksByAlbum :many
SELECT ar.name AS artist_name, al.title AS album_title, t.title, t.position, t.mbid, t.length_ms, t.local
FROM tracks t
JOIN albums al ON al.id = t.album_id
JOIN artists ar ON ar.id = al.artist_id
WHERE ar.name_norm = ? AND al.title = ?
ORDER BY t.position ASC
`

type ListTracksByAlbumRow struct {
	ArtistName string
	AlbumTitle string
	Title      string
	Position   int64
	Mbid       string
	LengthMs   int64
	Local      int64
}

func (q *Queries) ListTracksByAlbum(ctx context.Context, nameNorm string, title string) ([]ListTracksByAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByAlbum, nameNorm, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksByAlbumRow
	for rows.Next() {
		var i ListTracksByAlbumRow
		if err := rows.Scan(
			&i.ArtistName,
			&i.AlbumTitle,
			&i.Title,
			&i.Position,
			&i.Mbid,
			&i.LengthMs,
			&i.Local,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLocalTracks = `-- name: MarkLocalTracks :exec
UPDATE tracks SET local = (
    EXISTS (
        SELECT 1 FROM files
        JOIN albums al ON al.id = tracks.album_id
        JOIN artists ar ON ar.id = al.artist_id
        WHERE files.artist_norm = ar.name_norm
          AND files.album_norm = al.title_norm
          AND (
            files.title_norm = tracks.title_norm
            OR (files.track_number > 0 AND files.track_number = tracks.position)
          )
    )
    OR EXISTS (
        SELECT 1 FROM files
        JOIN albums al ON al.id = tracks.album_id
        JOIN artists ar ON ar.id = al.artist_id
        WHERE files.artist_norm = ar.name_norm
          AND files.title_norm != ''
          AND files.title_norm = tracks.title_norm
    )
)
WHERE album_id IN (
    SELECT al.id FROM albums al
    JOIN artists ar ON ar.id = al.artist_id
    WHERE ar.name_norm = ?
)
`

func (q *Queries) MarkLocalTracks(ctx context.Context, nameNorm string) error {
	_, err := q.db.ExecContext(ctx, markLocalTracks, nameNorm)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO tracks (album_id, title, title_norm, position, mbid, length_ms, local)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(album_id, title_norm) DO UPDATE SET
    title     = excluded.title,
    position  = excluded.position,
    mbid      = excluded.mbid,
    length_ms = excluded.length_ms,
    local     = excluded.local
`

type UpsertTrackParams struct {
	AlbumID   int64
	Title     string
	TitleNorm string
	Position  int64
	Mbid      string
	LengthMs  int64
	Local     int64
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.AlbumID,
		arg.Title,
		arg.TitleNorm,
		arg.Position,
		arg.Mbid,
		arg.LengthMs,
		arg.Local,
	)
	return err
}
